### ISSUE TITLE
Combine node-windows, node-linux and node-mac into one package

### ISSUE THREAD

**Issue by dotnetwise** [coreybutler/node-linux#10]
Using them individually doesn't make sense for a cross-platform service / package.

Can you please abstract them into a package e .g. `node-service` that would rely on all `node-windows`, `node-linux` and `node-mac` and use the appropriate one when running it. Auto-detect the current platform should be obviously easy.

What do you think?

**Comment by siarheidudko** [comment]
I want to write a project using node-windows and node-linux simultaneously, depending on the OS. But I cannot install both packages at the same time (OS dependency upon installation)

**Comment by coreybutler** [comment]
@siarheidudko - Combining the projects is no longer necessary. In fact, it would create unnecessary bloat to include the Windows .exe files in a Linux distro.

Your project can include all three projects if you like. npm will recognize which is appropriate for the OS your module is installed on and ignore the others. This is possible because each of the node-* projects specify which OS they're appropriate for. See [lines 20-22 of this project's package.json](https://github.com/coreybutler/node-linux/blob/master/package.json#L20-L22) as an example.

In your own project's `package.json`, you'd add each library you want as a dependency:

```
dependencies: {
  "node-windows": "^0.1.14",
  "node-mac": "^0.1.8",
  "node-linux": "^0.1.11"
}
```

**Comment by mfechner** [comment]
> ```
> dependencies: {
>   "node-windows": "^0.1.14",
>   "node-mac": "^0.1.8",
>   "node-linux": "^0.1.11"
> }
> ```

thanks for the tip, I just tested it, as I have exactly the same requirement.
I added all three packages as requested, but if I try now to do a `npm i` on a windows host, I get the error message (and the installation breaks:
```
$ npm i
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-mac@0.1.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-02-03T13_40_20_343Z-debug.log
```

**Comment by coreybutler** [comment]
I suppose the only way to really support that is to remove the OS restriction in the package. I'll have to think through the ramifications of doing that, but to hack around it, you might be able to use an npm postinstall script to install the OS-appropriate package. Certainly not ideal, but it should work.

**Comment by giegiey** [comment]
pls try 
npm install -f

> > ```
> > dependencies: {
> >   "node-windows": "^0.1.14",
> >   "node-mac": "^0.1.8",
> >   "node-linux": "^0.1.11"
> > }
> > ```
> 
> thanks for the tip, I just tested it, as I have exactly the same requirement.
> I added all three packages as suggested, but if I try now to do a `npm i` on a windows host, I get the error message (and the installation breaks):
> 
> ```
> $ npm i
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for node-mac@0.1.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-02-03T13_40_20_343Z-debug.log
> ```
> 
> I tested it with npm version 6.13.6.

Hey mate,

You can try 

`npm install -f`

**Comment by giegiey** [comment]
> > ```
> > dependencies: {
> >   "node-windows": "^0.1.14",
> >   "node-mac": "^0.1.8",
> >   "node-linux": "^0.1.11"
> > }
> > ```
> 
> thanks for the tip, I just tested it, as I have exactly the same requirement.
> I added all three packages as suggested, but if I try now to do a `npm i` on a windows host, I get the error message (and the installation breaks):
> 
> ```
> $ npm i
> npm ERR! code EBADPLATFORM
> npm ERR! notsup Unsupported platform for node-mac@0.1.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm ERR! notsup Valid OS:    darwin
> npm ERR! notsup Valid Arch:  any
> npm ERR! notsup Actual OS:   win32
> npm ERR! notsup Actual Arch: x64
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-02-03T13_40_20_343Z-debug.log
> ```
> 
> I tested it with npm version 6.13.6.

hey friend,

you need to use this

`npm install -f`

**Comment by linonetwo** [comment]
Hi, you can move them to `optionalDependencies` like:

```json
{
  "optionalDependencies": {
    "node-linux": "^0.1.12",
    "node-mac": "^0.1.8",
    "node-windows": "^1.0.0-beta.1"
  }
}
```
