### ISSUE TITLE
Spurious dependency of the "system" command

### ISSUE THREAD

**Issue by RazZziel** [coreybutler/node-linux#14]
In lib/systemv.js:272 your call "service $(this.label) start" to start a service', but that's not the standard SystemV way of starting scripts, I think it's only a shortcut available in Debian and Ubuntu.

A more portable/standard way would be:

        var cmd = '/etc/init.d/'+this.label+' start';
        console.log(cmd);
        exec(cmd,function(err){ ...

If you agree I'll submit a pull request

**Comment by coreybutler** [comment]
Good call, I'd accept that.
