### ISSUE TITLE
Amazon Linux

### ISSUE THREAD

**Issue by LeandroFavero** [coreybutler/node-linux#29]
Hi,

First: Thanks a lot to create this module! It's really very useful.

I was trying use in Amazon Linux and I get the problem in systemv.js
cat /proc/version get a undefined _os. Parse it's a little different.

This is the answer in Amazon Linux:
cat /proc/version
Linux version 4.1.17-22.30.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Fri Feb 5 23:44:22 UTC 2016

You can use Amazon Linux like a RedHat!

**Comment by coreybutler** [comment]
I've added the changes to the systemv.js file. I haven't pushed this to npm yet. Can you test this and let me know if it fixes the problem you're running into?

**Comment by LeandroFavero** [comment]
Works very well.

Just one warning (I'm using 5.8.0):
Installing service on /etc/init.d/test
(node) Buffer.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

**Comment by coreybutler** [comment]
The buffer warning is in a dependency. Neither of the dependencies are maintained anymore, so I'll have to look into alternatives. For now, I'm publishing this to npm as version 1.8.
